# Profile for setting snakemake options relevant for the SLURM scheduler

# Maximum number of jobs snakemake can submit at any one time
jobs: 100

# Tells it to use conda environments specified in rules
use-conda: true

# Number of cores snakemake can use locally
cores: 10

# Tell snakemake that we will be using SLURM as our job scheduler
executor: slurm

# Default resources for a rule
default-resources:
  runtime: 60  # in MINUTES
  slurm_partition: "cclake-himem"
  slurm_account: "JIGGINS-SL3-CPU"
  slurm_extra: "--mail-type=FAIL --output=logs/slurm/%x.%j.out --error=logs/slurm/%x.%j.err"

# Set specific resources for specific rules
set-resources:
  trim_filter_fastqs:
    cpus_per_task: 5
    slurm_extra: "--mail-type=ALL"
    runtime: 10

set-threads:
  trim_filter_fastqs: 5